### ISSUE TITLE
Precompilation of SymbolServer broken on Julia 1.11.0-DEV

### ISSUE THREAD

**Issue by George9000** [julia-vscode/SymbolServer.jl#278]
Please see [this issue](https://github.com/JuliaLang/julia/issues/52021) opened on the Julia repo.

"SymbolServer code [is] trying to do things with the core `array` intrinsics...[which] mostly no longer exist"

**Comment by Liozou** [comment]
This has already been fixed last week ago by https://github.com/julia-vscode/SymbolServer.jl/pull/276 but no release version has been tagged yet to make the bugfix visible. @pfitzseb do you want to tag a release? This was also asked by https://github.com/julia-vscode/SymbolServer.jl/issues/275.

Note that SymbolServer will remain bugged on julia master because of  https://github.com/JuliaLang/julia/pull/51878#issuecomment-1784769226 for the time being.

**Comment by pfitzseb** [comment]
master now works on Julia nightly again.
